update for 3.12
aws-samples/amazon-textract-textractor pull request #311
Opened 2024-02-19 23:38 UTC by tb102122

*Issue #, https://github.com/aws-samples/amazon-textract-textractor/issues/288

*Description of changes:*
Extend logic to run on python 3.12

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-28 22:15 UTC, tb102122 commented
@Belval @schadem Can you please let me know when it can be released. This is the only libary blocking my update to new lambda version python 3.12.

2024-02-28 23:25 UTC, tb102122 commented
> Could you update your PR to not include formatting changes? 
Done

2024-02-28 23:45 UTC, Belval requested changes

2024-02-28 23:45 UTC, Belval commented on textractor/entities/bbox.py
> +    By default :class:`BoundingBox` is set to work with denormalized co-ordinates: :math:`x in [0, docwidth]` and :math:`y in [0, docheight]`. \
Please revert this change as well, as it will break our documentation.

2024-02-28 23:46 UTC, Belval commented
We should also bump Textractor's version but I can take care of it. cc'ing @kmascar

2024-02-29 00:05 UTC, tb102122 commented
> We should also bump Textractor's version but I can take care of it. cc'ing @kmascar

done

2024-02-29 21:58 UTC, tb102122 commented
@Belval thanks for the changes let me know if I should do anythin else.

2024-03-01 17:01 UTC, Belval commented
We are still verifying that bumpinmg all the dependencies will not cause any issue, in the meantime if you are using Textractor I did partially merge your changes and will deploy them as part of 1.7.5 if everything passes: https://github.com/aws-samples/amazon-textract-textractor/actions/runs/8114500070/job/22180282101

2024-03-01 17:02 UTC, Belval commented
> I addit numpy in the root requirments.txt since it is needed for some tests.

Numpy is part of the extras: https://github.com/aws-samples/amazon-textract-textractor/blob/master/extras/dev.txt we don't enforce it as part of the minimum dependencies as most customers don't need it.

2024-03-05 10:22 UTC, miah0x41 commented
If the intention is not to support later versions of `numpy` beyond `1.21` then it means anything that uses `pandas` or `[dev]` libraries will be restricted to Python 3.10 or below.

Is it possible to at least then document this somewhere?

2024-03-05 19:22 UTC, Belval commented
> If the intention is not to support later versions of numpy beyond 1.21

This is not the intention, let me run a few tests without the pin.

2024-03-07 04:05 UTC, tb102122 commented
> We are still verifying that bumping all the dependencies will not cause any issue, in the meantime if you are using Textractor I did partially merge your changes and will deploy them as part of 1.7.5 if everything passes: https://github.com/aws-samples/amazon-textract-textractor/actions/runs/8114500070/job/22180282101

Sorry I have missed this comment. The build is working now please check if the layer is build correctly.

2024-03-07 13:40 UTC, Belval commented
Thank you for that fix, that's very helpful, were you able to find documentation on why yum is no longer available in the lamdba images?

2024-03-07 14:12 UTC, tb102122 commented
> Thank you for that fix, that's very helpful, were you able to find documentation on why yum is no longer available in the lamdba images?

Yes here you go. 

https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/

2024-03-07 22:46 UTC, Belval approved these changes

2024-03-07 22:50 UTC, tb102122 commented
@Belval Do you like me to take care of any of the warnings?
The failure is due to permissions I assume or?

https://github.com/aws-samples/amazon-textract-textractor/actions/runs/8182712664

2024-03-07 22:56 UTC, Belval commented
Those will resolve once the PR is merged, no action needed on your side.

2024-03-07 23:04 UTC, merged

2024-03-07 23:05 UTC, Belval commented
Thank you for your contribution.