add documentDim for different page orientations
aws-samples/amazon-textract-textractor pull request #70
Opened 2022-02-18 03:42 UTC by tb102122

extend function get bounding box to handle multipage documents with differnt orientations

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-23 18:36 UTC, schadem requested changes

2022-02-23 18:36 UTC, schadem commented on overlayer/textractoverlayer/t_overlay.py
> -class BoundingBox():
Can you use the style.yapf to format the code. It has column_limit: 120 and would make reading the changes easier.

2022-02-28 22:28 UTC, schadem commented
This is a good find. Thx!
I think we should rename the DocumentDimensions to DocumentDimension as well as it is really only one dataclass and not a list. Breaking changes to APIs, but we are still early with the helpers.
Also have to check how this effects the helper.
One comment about the formatting. Would be much easier if you take the formatting from master for the changes, then I can more easily compare and reason about what changed.
Good stuff!

2022-02-28 22:34 UTC, tb102122 commented
> This is a good find. Thx! I think we should rename the DocumentDimensions to DocumentDimension as well as it is really only one dataclass and not a list. Breaking changes to APIs, but we are still early with the helpers. Also have to check how this effects the helper. One comment about the formatting. Would be much easier if you take the formatting from master for the changes, then I can more easily compare and reason about what changed. Good stuff! I promise to have a quicker turnaround - been quite swamped last week...

Yes I thought about the same for the renaming but did not feel comfortable to do the changes since it is a breaking change.

Sorry about the formatting I di the setup now and it should work for future PRs. I will have some more in the coming weeks since I work more with the helpers for one of my projects. No worries about the turnaround.

2022-02-28 22:50 UTC, merged